config/routes.rb
Rails.application.routes.draw do
  get 'user_session/home'
  get 'reviews/home'
  get 'reviews/select_modal'
  get 'reviews/show_regression'

  get 'user_session/add_metric'

  get 'user_session/add_event'

  get 'user_session/define_metric'

  get 'user_session/define_event'
  get 'user_session/chart'
  get 'reviews/chart'

  get 'user_session/refresh'
  get 'duser_metrics/show_unit_display'
  get 'duser_metrics/filter_table_rows'
  post 'user_session/home', to: 'user_session#changes'
  post 'duser_metrics/create', to: 'duser_metrics#create'
  post 'duser_metrics/edit', to: 'duser_metrics#edit'
  post 'user_session/delete', to: 'duser_metrics#destroy'
  post 'duser_metrics', to: 'duser_metrics#create'
  post 'user_session/toggle_metric_visible', to: 'metrics#toggle_metric_visible'

  patch 'duser_metrics/save_duser_metric_table'
  get 'duser_metrics/chart'
  delete 'duser_metrics/destroy'

  resources :duser_metrics
  resources :units
  resources :metrics
  resources :reviews

  devise_for :dusers

  get 'welcome/greeting'
  get 'welcome/about'

  get 'welcome/doc'
  get 'welcome/home'

  get 'metric/add'

  get 'metric/edit'

  get 'metric/delete'

  root 'welcome#greeting'

end

app/views/shared/_duser_metric_table.html.erb
  

        <!--div class="col-md-8" id="createnewmetricform"--> 
          <%= form_tag({ :controller => "duser_metrics", :action => "save_duser_metric_table"},{ :method => "patch"} ) do %>  


                <table id="thetable" class="thetable">  <!-- style in user_session.scss -->
                <thead>
                <tr>
                  <th> Metric </th>
                  <th> Value </th>
                  <th> Units </th>
                  <th> Datetime </th>
                  <th> Del </th>
                  <th> Edit </th>
                  <th> Copy </th>
                </tr>
                </thead>
                <tbody>
                <!--
                  If there are no metrics charted, add an empty one to get started.
                -->
                <% for duser_metric in @displayed_series %>  
                  <%= render partial: "shared/duser_metric_tr", locals: {duser_metric: duser_metric} %> 
                <% end %>  
                </tbody>
                <tfoot >
                  <tr><td colspan=7 align="center">End of listing </td></tr>
                </tfoot>
                </table>
<style type="text/css">
  
.checkmark  {
  font-style: italic;
  font-size: smaller;
  color: green; 
}
.checkmark:after {
    content: '\2713';
    color: green;
    padding: 5px;
}
 .list-group{
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    max-width: 1000px;
  }

  .list-group-item{
    min-width: 50px;
  }
  .fa-caret-down{
   font-size: 10;
   color:blue;
   font-weight: lighter 
  }
</style>                


                     <div  align="center" width="auto">
                     <%= submit_tag "Refresh Chart" , class: "btn btn-default" %>
                      <a class="btn btn-default btn-xs "  role="button" data-bs-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample" >
                        Filter Metrics
                       <span class="fa fa-caret-down" aria-hidden="true"></span>
                      </a>
                          <div class="collapse" id="collapseExample" >
                          <ul class="list-group list-group-horizontal" >
                            <%
                              metric_ids = @displayed_series.map { |m| m.metric_id }
                              metric_ids = metric_ids.uniq
                             for m_id in metric_ids 
                             %>  
                            <li>
                              <%= link_to Metric.find(m_id).name,  { id: m_id, remote: true, controller:"duser_metrics" , action: "filter_table_rows" } , {class: "list-group-item border-0 checkmark toggle_metric", id: "toggle_metric_" + m_id.to_s } %>
                              </li>
                            <%end%>
                            <li>
                              <a class="list-group-item border-0 checkmark toggle_metric" id="toggle_metric_0" data-remote="true" href="/duser_metrics/filter_table_rows?id=0">Show All</a>
                              </li>
                            <li>
                            <li>
                              <a class="list-group-item border-0 checkmark toggle_metric" id="toggle_metric_-1" data-remote="true" href="/duser_metrics/filter_table_rows?id=-1">Hide All</a>
                              </li>
                            <li>
                          </ul>
                          </div> <!-- end of collapse class-->

                   </div> <!-- end of align-->
      <% end #end of form %>  

<div id="duser-metric-modal" class="modal fade"></div>

              <%# if @displayed_series.none? %>
              <%#=  link_to 'my_link', :new_duser_metric , remote: true ,hidden: true, id: "salt-row-for-new-user" %>
              <%#  #controller.redirect_to :new_duser_metric, remote: true, modal: true%>
              <%# end %>

              <!-- The following creates a dropdown button with select options
                        The options are taken from the @m collection. The first 2 options are the 
                        name of the object (metric) and the column in the object (id) to set in the 
                        select tag attributes as name="metric[id]" and id="metric_id".  This is added to 
                        the url as a parameter for the Ajax call to "filter_table_rows".  This in turn 
                        will either display or hide the rows in the table.  Purpose is to help the user
                        see the data in the table by grouping entries of a selected type together.

                    01/22/24 Replaced the dropdown list with the collapsable list group. The list group
                    shows well horizontally and is a little more flexible than the dropdown list.  Kept this 
                    collection_select code around for reference, since it was originally difficult to work out.
                    -->

                   <%# @m = Metric.where( " duser_id = 1 or duser_id = ?", current_duser.id ) %>
                   <%#= collection_select(:metric,:id,@m, :id, :name,{include_blank: 'Clear Filter'}, 
                     { :data => { remote: true, :url => url_for(:controller => "duser_metrics", :action => "filter_table_rows") },multiple: false }
                     )
                   %>

app/views/shared/_duser_metric_tr.html.erb

<tr class="tr_clone" id="tr_clone_<%=duser_metric.id.to_s%>" >
<%= fields_for "duser_metrics[]", duser_metric do |f| %>  
   <td> 
        <%#
         This collection select displays the name of the charted metric, along with a dropdown
         list of other metrics available to the user.  If a different metric is selected, 
         a call is made to 'show unit display', which updates DuserMetric table with the new 
         metric_id, and changes the Units display to the one assigned to the new metric. Finally,
         the chart is updated to remove the value from the old series, and add it to the new.
        %>
        <%# get all the metrics that are either system provided or this user created %>
        <% @m = Metric.where( " duser_id = 1 or duser_id = ?", current_duser.id ) %>
        <%# Now create the select list and tie it to a ujs call to 'show_unit_display' %>
        <%=f.collection_select(:metric_id, @m, :id, :name,{}, 
          { :data => { remote: true,
                       :url => url_for(:controller => "duser_metrics", 
                       :action => "show_unit_display",
                       :id => duser_metric.id.to_s)
         }}) %>
    </td>
   <td>
    <%#= f.number_field :value ,data: {remote: true, method: :patch,url: duser_metric_path(id: duser_metric.id, value: duser_metric.value)} %> 
    <%= f.number_field :value ,data: {remote: true, method: :patch,url: duser_metric_path(duser_metric)} %> 
   </td>

   <%= render partial: "shared/metric_unit_display", locals: {duser_metric: duser_metric} %> 

   <td> 
      <%#= f.text_field :occur_dttm , class: "default_datetimepicker mydatetimeInput" ,data: {remote: true, method: :patch,url: duser_metric_path(duser_metric)}%> 

      <%= f.datetime_field :occur_dttm,data: {remote: true, turbo: false, method: :patch,url: duser_metric_path(duser_metric)}%> 
   </td>
   <td>
   <%= link_to duser_metric,:class => "btn btn-default btn-xs tr_clone_remove_btn",:method =>"delete", :remote => true do %>
      <span class="fa fa-remove" aria-hidden="true" style="color:red; font-size: 10px; font-weight: lighter "></span>
   <% end %>  
   </td>
   <td>
   <%= link_to duser_metrics_edit_path(:id => duser_metric.id.to_s),:controller => "duser_metrics", :action => "edit",  :class => "btn btn-default btn-xs tr_clone_edit_btn" , :method => "post", data: { remote: true, modal: true } do %>
      <span class="fa fa-pencil" aria-hidden="true" style="color:black; font-size: 10px; font-weight: lighter "></span>
   <% end %>  
   </td>
   <td>
   <%= link_to duser_metrics_create_path(:clone_id => duser_metric.id.to_s),:controller => "duser_metrics", :action => "create",:class => "btn btn-default btn-xs tr_clone_add_btn", :method => "post", :remote => true do %>
      <span class="fa fa-plus" aria-hidden="true" style="color:blue; font-size: 10px; font-weight: lighter "></span>
   <% end %>  
   </td>
<% end %>  
</tr>


app/views/shared/_footer.html.erb
<footer class="footer">
  <small>
    The MyLife Biometric Charting by: 
    <%= if current_duser != nil
      current_duser.username.to_str  
      else 
        "Not Logged In"
        end
    %>
    <%#=session_message%>
  </small>
    <ul>
      <li><%= link_to "Footer Link ",   '#' %></li>
      <li><a href="#">Footer href</a></li>
    </ul>
</footer>

app/views/shared/_greeting_with_content.html.erb

   <div class="container">
        <div class="row">
          <div class="col-md-8">
            <h1>Capture <span class="em-text">Life</span></h1>
            <p>
             <%= image_tag "chart_bg2.png", class: "jumbotron_in_session" %> 
            </p>
            <p>An easy way to capture & share your vital numbers</p>
            <p>Find me in app/views/shared/_greeting_with_content.html.erb</p>
         </div>
           <div class="col-md-4 auth_message">
            <%= render partial: action_name %>
            <%= show_params %>
            <p> <%= request.path %> </p>
            <p> <%= request.env['ORIGINAL_FULLPATH'] %> </p>
            <% if devise_controller? %>
              <p> This is a devise controller </p>
            <%else%>
              <p> This is NOT a devise controller </p>
            <%end%>
          </div>

      </div>

    </div>

app/views/shared/_metric_unit_display.html.erb
<td id="show_unit_display_<%=duser_metric.id.to_s %>"> <%= Unit.find(duser_metric.metric.unit_id).displ_name %> </td>

app/views/shared/_navbar_default.html.erb
<nav class="navbar sticky-top navbar-expand-md navbar-light bg-light ">
  <div class="container-fluid">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 <a class="navbar-brand" href="#">
  <%#
    Look in the packs/manifest.json file for the path to the image, and use that with the image_pack_tag
  %>
  <%= image_tag("44px-Wiki_letter_w.svg.png", :class => "d-inline-block align-top", :title => "Whodabudda") %> 
    Whodabudda
  </a>
 
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%#
      #Have to turn off turbolinks for this as it loses the javascript when re-directed from
      #welcome/home.  Turbolinks is likely to go away soon in favor of Turbo from Hotwire, which
      #will be standard starting with Rails 7.
      #
      %>
      <li class="nav-item <%= 'active' if current_page?(root_path) %>"><%= link_to 'Home', root_path,:class => 'nav-link',:"data-turbo" => false %></li>
      <li class="nav-item <%= 'active' if current_page?(welcome_about_path) %>"><%= link_to 'About', welcome_about_path ,:class => 'nav-link'%></li>
      <li class="nav-item <%= 'active' if current_page?(welcome_doc_path) %>"><%= link_to 'Doc', welcome_doc_path ,:class => 'nav-link'%></li>
     <!--
      <li class="nav-item btn-group">
         <a class="dropdown-toggle nav-link" href="#" type="button" id="navbarDropdownMenuLink1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          New Content
         </a>
         <div class="dropdown-menu" role="menu" aria-labelledby="navbarDropdownMenuLink1">
              <%#= link_to 'New Metric',  [:new ,"metric".underscore ], :class => "dropdown-item"  %>
              <%#= link_to 'New Unit',  [:new ,"unit".underscore ], data: { remote: true, modal: true }, :class => "dropdown-item" %>
              <%#= link_to 'New Value', [:new ,"duser_metric".underscore ],data: { remote: true, modal: true } , :class => "dropdown-item" %> 
         </div>
      </li>
    -->
      <%# this is new navbar menu syntax for bootstrap 5 %>
      <%if duser_signed_in? %>
      <li class="nav-item dropdown">
         <a class="nav-link dropdown-toggle" href="#" role="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Manage Content
         </a>
         <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>  
              <%# The next 2 links will create a modal window for a new metric and unit respectively. Changed it to be an index view %>
              <%#= link_to 'Metrics',  [:new ,"metric".underscore ],data: { remote: true }, :class => "dropdown-item"  %>
              <%#= link_to 'New Unit',  [:new ,"unit".underscore ], data: { remote: true }, :class => "dropdown-item" %>
              <%= link_to 'Metrics',  :metrics, :class => "dropdown-item"   %>
            </li>
            <li>  
              <%= link_to 'Units',  :units, :class => "dropdown-item"   %>
            </li>
         </ul>
      </li>

      <li class="nav-item dropdown">
         <a class="nav-link dropdown-toggle" href="#" role="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Settings 
         </a>
         <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>  
              <%= link_to 'Under Construction',  "#", :class => "dropdown-item" if duser_signed_in?  %>
            </li>
          </ul>
      </li>

      <li>
        <%= link_to 'Analysis', reviews_home_path , :class => 'nav-link' if duser_signed_in? %>
      </li>

      <li>
        <%= link_to 'Log Off', destroy_duser_session_path , method: :delete,:class => 'nav-link' if duser_signed_in? %>
      </li>
      <%end%>
    </ul>
    <%#
      I don't know why the class format for the session message puts the message to the right of the container, but it does (this is the desired behaviour)
      Got the hint from:  https://stackoverflow.com/questions/63948287/bootstrap-5-navbar-align-items-right
    %>
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
         <li class="nav-item"> 
             <%= session_message %>
         </li>
    </ul>
  </div>
</div>
</nav>

app/views/shared/_review_sidebar.html.erb
<!-- The sidebar -->
<div class="sidenav">
<%  review = local_assigns.fetch(:review, @review) %>
 
  <%Rails.logger.info "review:sidebar persisted: #{@review.persisted?} inspect:  #{@review.inspect}" %>
  <%#=Rails.logger.info "review_valid:sidebar inspect:  #{@review_valid.inspect}" %>

  <%= render partial: 'form', locals: {review: @review, post_method: @review.valid? ? true : false} %>

  <!--hr class="solid"-->

  <!-- 
    The "post_review" class is a placeholder for the POST or PATCH form that calls review#create or review#update respectively to save the review to the database.  You can't redirect_to a POST method from a GET method. Apparently that is built into http.  We want the user to be able to play with the fields in the GET form until they come up with something they want to save. Each time they change a field in the GET form, show_regression is called.  When the form passes all its validations, the javascript in show_regression.js.erb will execute and the submit button for the POST/PATCH method will be enabled. The user can then save the valid review.
  -->

  <!-- 
      When the review_sidebar is first rendered, there is  no POST form.  If the model was created by selecting a previously saved review, the 'patch' method is used which calls the 'update' action, otherwise a new review via the'post' method and 'create' action is used.
  -->
  <div class="saved_reviews">
  <%= link_to 'Saved Reviews', :reviews_select_modal,data: { remote: true } %> 
  </div>
</div>

  <!-- 
    This link_to method was an experiment in how to get an anchor tag to do a POST/PATCH method. The keys to making it work were to set the review params from a json hash, set the id to "" if there is no id in review, and set the method based on if there is an id or not.  The presence of an id indicates the model variable came from the database.  There were still problems with this approach, and sending the data in a form works better.
  -->
  <%#= link_to "Save" , review_path( @review.id.nil? ? "" : @review.id, controller: :review, review: @review.as_json), method: @review.id.nil? ? :post : :patch , data: { turbo: false}%>

app/views/shared/_tree_sidebar.html.erb
<%#
The offcanvas class is a component of bootstrap:
  https://getbootstrap.com/docs/5.0/components/offcanvas/#via-data-attributes
  data-bs-scroll enables/disables scrolling in the backdrop, and allows the offcanvas to be closed on click
  data-bs-backdrop enables/disables action on the canvass (no close on click) while offcanvas is shown

  The canvass can be positioned in all 4 directions
  Most bootstrap elements can be used in the offcanvas area

  Currently, the offcanvas should close as soon as a selection is made so that the main window can be used with 
  any changes triggered by a selection from offcanvas 
%>
<div class="offcanvas offcanvas-start w-2" tabindex="-1" id="offcanvas" data-bs-scroll="true" data-bs-keyboard="false" data-bs-backdrop="true">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title d-none d-sm-block">Offcanvas</h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
<div class="offcanvas-body px-0">
<h3 id="tree1">
  Foods
</h3>
<ul role="tree" aria-labelledby="tree1" class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-start" id="menu">
  <li role="treeitem" aria-expanded="false">
    <span>
      Fruits
    </span>
    <ul>
      <li role="none">
        <%= link_to 'Home', root_path,:role => 'treeitem',:"data-turbolinks" => false %>
      </li>
      <li role="none">
        <a role="treeitem" href="https://en.wikipedia.org/wiki/Pineapple">
          Pineapple
        </a>
      </li>
      <li role="treeitem" aria-expanded="false">
        <span>
          Apples
        </span>
        <ul role="group">
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/McIntosh_%28apple%29">
              Macintosh
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Granny_Smith">
              Granny Smith
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Fuji_(apple)">
              Fuji
            </a>
          </li>
        </ul>
      </li>
      <li role="none">
        <a role="treeitem" href="https://en.wikipedia.org/wiki/Banana">
          Bananas
        </a>
      </li>
      <li role="treeitem" aria-expanded="false">
        <span>
          Pears
        </span>
        <ul role="group">
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/D%27Anjou">
              Anjou
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Williams_pear">
              Bartlett
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Bosc_pear">
              Bosc
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Pyrus_communis">
              Concorde
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Pyrus_communis">
              Seckel
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Pyrus_communis">
              Starkrimson
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </li>
  <li role="treeitem" aria-expanded="false">
    <span>
      Vegetables
    </span>
    <ul role="group">
      <li role="treeitem" aria-expanded="false">
        <span>
          Podded Vegetables
        </span>
        <ul role="group">
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Lentil">
              Lentil
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Pea">
              Pea
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Peanut">
              Peanut
            </a>
          </li>
        </ul>
      </li>
      <li role="treeitem" aria-expanded="false">
        <span>
          Bulb and Stem Vegetables
        </span>
        <ul role="group">
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Asparagus">
              Asparagus
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Celery">
              Celery
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Leek">
              Leek
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Onion">
              Onion
            </a>
          </li>
        </ul>
      </li>
      <li role="treeitem" aria-expanded="false">
        <span>
          Root and Tuberous Vegetables
        </span>
        <ul role="group">
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Carrot">
              Carrot
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Ginger">
              Ginger
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Parsnip">
              Parsnip
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Potato">
              Potato
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </li>
  <li role="treeitem" aria-expanded="false">
    <span>
      Grains
    </span>
    <ul role="group">
      <li role="treeitem" aria-expanded="false">
        <span>
          Cereal Grains
        </span>
        <ul role="group">
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Barley">
              Barley
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Oats">
              Oats
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Rice">
              Rice
            </a>
          </li>
        </ul>
      </li>
      <li role="treeitem" aria-expanded="false">
        <span>
          Pseudocereal Grains
        </span>
        <ul role="group">
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Amaranth">
              Amaranth
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Buckwheat">
              Bucketwheat
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Salvia_hispanica">
              Chia
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Quinoa">
              Quinoa
            </a>
          </li>
        </ul>
      </li>
      <li role="treeitem" aria-expanded="false">
        <span>
          Oilseeds
        </span>
        <ul role="group">
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Brassica_juncea">
              India Mustard
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Safflower">
              Safflower
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Flax_seed">
              Flax Seed
            </a>
          </li>
          <li role="none">
            <a role="treeitem" href="https://en.wikipedia.org/wiki/Poppy_seed">
              Poppy Seed
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
</div>
</div>