config/routes.rb
Rails.application.routes.draw do
  get 'user_session/home'
  get 'reviews/home'
  get 'reviews/select_modal'
  get 'reviews/show_regression'

  get 'user_session/add_metric'

  get 'user_session/add_event'

  get 'user_session/define_metric'

  get 'user_session/define_event'
  get 'user_session/chart'
  get 'reviews/chart'

  get 'user_session/refresh'
  get 'duser_metrics/show_unit_display'
  get 'duser_metrics/filter_table_rows'
  post 'user_session/home', to: 'user_session#changes'
  post 'duser_metrics/create', to: 'duser_metrics#create'
  post 'duser_metrics/edit', to: 'duser_metrics#edit'
  post 'user_session/delete', to: 'duser_metrics#destroy'
  post 'duser_metrics', to: 'duser_metrics#create'
  post 'user_session/toggle_metric_visible', to: 'metrics#toggle_metric_visible'

  patch 'duser_metrics/save_duser_metric_table'
  get 'duser_metrics/chart'
  delete 'duser_metrics/destroy'

  resources :duser_metrics
  resources :units
  resources :metrics
  resources :reviews

  devise_for :dusers

  get 'welcome/greeting'
  get 'welcome/about'

  get 'welcome/doc'
  get 'welcome/home'

  get 'metric/add'

  get 'metric/edit'

  get 'metric/delete'

  root 'welcome#greeting'

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  #has_many :dusers , :through => :metrics
  belongs_to :duser
  has_many :metrics
  #
  #name of unit must be unique within the duser_id
  #TODO investigate the value of doing a cascading delete.
  #Right now, a delete of a Unit in use will orphan the using record.
  #
  #select all the units a user is authorized to view.  The views themselves will have to
  #manage what this user can edit in the unit.
  #
  scope :auth_to_view, ->(pduser_id) { where("units.duser_id in (?)",[pduser_id,Duser.system_user]).order(:duser_id,:name) }
  validate :unique_name_for_new, on: :create
  validate :unique_name_for_edit, on: :update

private

  def unique_name_for_new
    if Unit.exists?(name: name, duser_id: [duser_id, Duser.system_user])
      errors.add(:name, 'has already been taken')
    end
  end

  def unique_name_for_edit
    # when editing, if changing the name, make sure the new name doesn't exist
    if name_changed? && Unit.exists?(name: name, duser_id: [duser_id, Duser.system_user])
      errors.add(:name, 'has already been taken')
    end
  end
  #
  #validates_uniqueness_of :name within duser_id and system_user_id
  #Instead of copying all the system-defined Units and Metrics for the new user, will make
  #them available to all users, and check for uniqueness of name against both current_duser.id and 
  #system duser_id.
  #
=begin
  before_create :check_unique_name_for_new
  before_update :check_unique_name_for_edit
  def check_unique_name_for_new
    if Unit.select(:duser_id).where("name = ? and duser_id in (?)",self.name, [self.duser_id, Duser.system_user]).count > 0
     errors.add(:name, "has already been taken")
     raise ActiveRecord::RecordNotUnique.new(self)
    end
  end
  def check_unique_name_for_edit
    #when editing, if changing the name, make sure the new name doesn't exist
    if Unit.find(self.id).name != self.name
       check_unique_name_for_new
    end
  end
=end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  class NotAuthorized < StandardError
 end

  before_action :set_unit_for_change, only: [:edit, :update, :destroy]
  before_action :set_unit_for_view, only: [:show]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  rescue_from NotAuthorized, with: :not_authorized
#  rescue_from ActiveRecord::RecordNotUnique, with: :not_unique

  respond_to :html, :json, :js
  layout 'modal', only: [:new,:edit]
  # GET /units
  # GET /units.json
  def index
    @units = Unit.auth_to_view(current_duser.id)
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
    @unit.duser_id = current_duser.id
#    respond_to do |format|
#      format.html { render :new }
#    end
    #render
  #respond_modal_with @unit , layout: "modal"
    
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)
    raise NotAuthorized unless (@unit.duser_id == current_duser.id)  #just to be safe
    respond_to do |format|
      if @unit.save
        #format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.html { redirect_back fallback_location: root_path, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.js
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_back fallback_location: root_path , notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.js 
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    Metric.where(unit_id: @unit.id).where( duser_id: @unit.duser_id).destroy_all

    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.0
    # Only allow access to edit if user is system_user or owns the unit
    # guard against somone spoofing a different duser_id in the message
    def set_unit_for_view
      @unit = Unit.find(params[:id])
      raise RecordNotFound unless !@unit.nil?
      raise NotAuthorized unless [Duser.system_user, current_duser.id].include? @unit.duser_id 
    end
    def set_unit_for_change
      @unit = Unit.find(params[:id])

      raise RecordNotFound unless !@unit.nil?
      raise NotAuthorized unless current_duser.id == @unit.duser_id 

      Rails.logger.info "params has duser_id key: #{params.dig(:unit,:duser_id) }"
      if params.dig(:unit,:duser_id)
        #Rails.logger.info "params key same as user?: #{params.dig(:unit,:duser_id).to_i == current_duser.id }"
        raise NotAuthorized unless (params.dig(:unit,:duser_id).to_i == current_duser.id)
      end
    end

    def record_not_found
      render plain: "404 Not Found : no record for id: " #+ @metric.id + " user_id: " + @metric.duser_id, status: 404
    end
    def not_authorized
      Rails.logger.info "Raised NotAuthorized in: #{params[:controller]} : #{params[:action]}  for user: " + current_duser.id.to_s
      flash[:notice] = "You don't have access to this record."
      redirect_back(fallback_location: root_path)
    end

    def not_unique(exception)
      Rails.logger.info "Raised RecordNotUnique with error: #{exception.class} #{exception.message}"
      raise exception
      #render json: { error: exception }, status: :unprocessable_entity, notice:  "This name is already in your list" 
      redirect_back(fallback_location: root_path, notice:  "This name is already in your list" )
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :displ_name, :duser_id)
    end

end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%#
<div class="modal-dialog" >
  <div class="modal-content" >
%>
<%= form_for @unit, remote: true, html: { style: "display:inline;" } do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%# add autocomplete off so that the browser built-in drop-down of previous entries doesn't show %>
    <%= f.text_field :name , autocomplete: "off"%>
  </div>
  <div class="field">
    <%= f.label :name_to_display %><br>
    <%= f.text_field :displ_name %>
  </div>
  <div class="field" hidden="true">
    <%= f.label :duser_id %><br>
    <%= f.text_field :duser_id, readonly: true%>
  </div>
  <div class="modal-footer actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>
<%#
  </div>
  </div>
%>

app/views/units/_new.html.erb
<%#= render 'form', layout: "modal" %>

app/views/units/create.js.erb
<% if @unit.errors.any? %>
  // Handle errors and update the modal form
  var errorsHtml = "<ul>";
  <% @unit.errors.full_messages.each do |message| %>
    errorsHtml += "<li><%= j message %></li>";
  <% end %>
  errorsHtml += "</ul>";

  $('#modal-error-messages-container').html(errorsHtml);
<% else %>
  // Close the modal or perform any other actions for success
  $('#exampleModal').modal("close")

<% end %>

app/views/units/edit.html.erb
<%= content_for :'modal-title'  do %>
   Editing Unit
<%end%>
<%= content_for :'modal-body'  do %>
<%= render "form" %>
<%end%>

<%= link_to 'Back', units_path %>

app/views/units/edit.js.erb
$("#modal-holder").html("<%= escape_javascript(render template: 'units/edit',formats: [:html], layout: 'layouts/modal') %>")
showModal('exampleModal')
//$('#exampleModal').modal("show")

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Units</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Displ name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <% auth = Duser.auth?(unit.duser_id, current_duser.id) %>
        <td><%= unit.name %></td>
        <td><%= unit.displ_name %></td>
        <%if auth %>
        <td><%#= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit), remote: true%></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path , remote: true%>

app/views/units/new.html.erb
<%= content_for :'modal-title'  do %>
   New Unit
<%end%>
<%= content_for :'modal-body'  do %>
<%= render "form" %>
<%end%>

<%= link_to 'Back', units_path %>

app/views/units/new.js.erb
//
//The layout has the framework for the modal. new.html.erb has content_for blocks to provide header and body
//content, which should make the layout generic for all modals.  You must have a div with modal-holder on the page
//this is launched from.  Since this is launched from the navbar, which includes the application layout where 
//modal-holder is defined.  Also note that the template: parm is used with render, meaning that if you give the  
//path to the view, it will use the full template, not the partial.
//
$("#modal-holder").html("<%= escape_javascript(render template: 'units/new',formats: [:html], layout: 'layouts/modal') %>")
showModal('exampleModal')
//$('#exampleModal').modal("show")

//
//Had a great deal of trouble getting both jquery and bootstrap modal function to work. 
//bootstrap defines the modal function, and somehow attaches it to jquery.
//It never worked with the ES6 import, but seems to be working now using 'require' for bootstrap
//Rails doc says not to use ES6 methods with ujs because ujs does not pre-process.  Yeah, that explains so much.

//
//Here are some troubleshooting things to try if it goes south again.
//
//console.log("the element is: " + document.querySelector('#exampleModal'));
//let mynewmodal = new Modal(document.getElementById('exampleModal'));
//console.log("mymodal is: " + mynewmodal)
//mynewmodal.show();

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<p>
  <strong>Displ name:</strong>
  <%= @unit.displ_name %>
</p>

<p>
  <strong>Duser:</strong>
  <%= @unit.duser %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) , remote: true%> |
<%= link_to 'Back', units_path %>

app/views/units/update.js.erb
<% if @unit.errors.any? %>
  // Handle errors and update the modal form
  var errorsHtml = "<ul>";
  <% @unit.errors.full_messages.each do |message| %>
    errorsHtml += "<li><%= j message %></li>";
  <% end %>
  errorsHtml += "</ul>";

  $('#modal-error-messages-container').html(errorsHtml);
<% else %>
  // Close the modal or perform any other actions for success
  $('#exampleModal').modal("close")

<% end %>