config/routes.rb
Rails.application.routes.draw do
  get 'user_session/home'
  get 'reviews/home'
  get 'reviews/select_modal'
  get 'reviews/show_regression'

  get 'user_session/add_metric'

  get 'user_session/add_event'

  get 'user_session/define_metric'

  get 'user_session/define_event'
  get 'user_session/chart'
  get 'reviews/chart'

  get 'user_session/refresh'
  get 'duser_metrics/show_unit_display'
  get 'duser_metrics/filter_table_rows'
  post 'user_session/home', to: 'user_session#changes'
  post 'duser_metrics/create', to: 'duser_metrics#create'
  post 'duser_metrics/edit', to: 'duser_metrics#edit'
  post 'user_session/delete', to: 'duser_metrics#destroy'
  post 'duser_metrics', to: 'duser_metrics#create'
  post 'user_session/toggle_metric_visible', to: 'metrics#toggle_metric_visible'

  patch 'duser_metrics/save_duser_metric_table'
  get 'duser_metrics/chart'
  delete 'duser_metrics/destroy'

  resources :duser_metrics
  resources :units
  resources :metrics
  resources :reviews

  devise_for :dusers

  get 'welcome/greeting'
  get 'welcome/about'

  get 'welcome/doc'
  get 'welcome/home'

  get 'metric/add'

  get 'metric/edit'

  get 'metric/delete'

  root 'welcome#greeting'

end

app/controllers/reviews_controller.rb
require 'rserve'
#require_dependency('h_s_series_regression')
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy home]
  before_action :show_params
  respond_to :html, :json, :js

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end
  def select_modal
    @reviews = Review.all
  end
  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|

      if @review.save
        format.html { render :home, id: @review.id, notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { render :home, id: @review.id, notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  # DELETE /reviews/1 as JS will remove row from select_modal window
  def destroy
    @review.destroy
    respond_to do |format|
      format.js 
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

 # home screen for Reviews
 #
 #the home action can be called from either the main navigation bar, in which case review.id will be nil,
 #or after an update or create action, where review.id will not be nil.
  def home
    @review = Review.new if @review.nil?
    #if the call to home is from selecting a previously saved review in the modal window, 
    #then use it and return
    if @review.persisted?
      @new_review = false
      return @review, @new_review
    end
    #otherwise, check if we have a previously saved review and use the most recent as the template for a new review.  
    #This way, the user can have a starter of data and won't overwrite what they already saved.
    #If there is no saved review, fill in some default values.
    @review_templ = Review.where(duser_id: [Duser.system_user,current_duser.id]).last
    if @review_templ.nil?
     @review.duser_id = current_duser.id
     @review.metric_id = DuserMetric.joins(:metric).select(:metric_id).where("metric.series_type": "metric", "duser_metrics.duser_id": current_duser.id).last
     @review.event_id = DuserMetric.joins(:metric).select(:metric_id).where("metric.series_type": "event", "duser_metrics.duser_id": current_duser.id).last
     @review.start_dt = Time.now - 14.days
     @review.end_dt = Time.now 
     @review.significant = false
     @review.span = 24
   else
    @review.assign_attributes(
      id: @review_templ.id,
      duser_id: @review_templ.duser_id,
      metric_id: @review_templ.metric_id,
      event_id: @review_templ.event_id,
      start_dt: @review_templ.start_dt,
      end_dt: @review_templ.end_dt,
      span: @review_templ.span,
      significant: @review_templ.significant
      )
    end
   Rails.logger.info "review:home inspect:  #{@review.inspect}" 
   @new_review = true
   return @review , @new_review
  end

  def get_regression_chart
  end

  # GET /reviews/1 or /reviews/1.json
  # The job of this action is to return a variable to the view that can be
  # evaluated for validations but won't affect the result of the '@review.persisted?' method.
  # The whole idea is to show the 'Save Review' button when the review passes validation,
  # but allow the 'form_with' helper to use the proper route, i.e. model: review for a 
  # new record, or review/:id for a revised record.
  def show_regression
    #byebug 
    # if there is an id in the params, then this is an existing record and we need
    # to modify the attributes without returning a Review.new variable. 
    id = 0
    stat_testname = params.dig(:testname)
    if params.dig(:review)
      id =  params.dig(:review,:id).to_i 
    else
      id =  params.dig(:id).to_i 
    end
    Rails.logger.info "ReviewsController:ShowRegression id: #{id}, params: review-> #{params.dig(:review,:id).to_i} no_review-> #{params.dig(:id)}" 

    #If we already have a saved review, the id will be > 0 and we assign the the possibly
    #changed attributes to the review from the database. Otherwise, create a new review object
    #and assign attributes.
    if id > 0
      @review = Review.find(id)
      @review.assign_attributes(show_regression_params)
    else
       @review = Review.new(show_regression_params)
    end
    Rails.logger.info "after getting parms, review is #{@review.inspect}" 
    Rails.logger.info "after getting parms, review.errors are #{@review.errors}"
  if(@review.validate) 
    begin
    #debugger
    @conn=Rserve::Connection.new
     # TODO - rescue StandardError
     # TODO - rescue_with_handler(StandardError)
    @reviewStats = ReviewStats.new(@review,@conn)
    @reviewStats.perform_analysis(stat_testname)

    #make sure, whatever happens, that the socket connection is closed. Otherwise we'll eventually
    #crash the server.
    ensure
      @conn.close
    end
    Rails.logger.info "stat_classes are #{@reviewStats.stat_classes}" 
  else
    Rails.logger.info "review did not validate, errors are #{@review.errors.full_messages}"
  end
    return @review, @reviewStats

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      id = 0
      if params.dig(:review)
       id =  params.dig(:review,:id).to_i 
      else
       id =  params.dig(:id).to_i 
      end

      @review = Review.find(id) if id > 0
      Rails.logger.info "in: #{params[:controller]} : #{params[:action]} review variable is: #{@review.nil? ? "nil" : true}"
    end
    # Only allow a list of trusted parameters through.
    def review_params
      #Rails.logger.info "review:params before extract! #{params.inspect}"
      params.require(:review).extract!(:created_at,:updated_at)
      params.require(:review).permit(:metric_id, :event_id, :duser_id, :start_dt, :end_dt, :span, :significant,:id)
      #Rails.logger.info "review:params after extract! #{params.inspect}"
    end
    def show_regression_params
      #any call from the form will have the review key
      if(params.has_key?(:review))
       params.require(:review).extract!(:created_at,:updated_at)
       params.require(:review).permit(:metric_id, :event_id, :duser_id, :start_dt, :end_dt, :span, :significant,:id,:testname)
      else
      #any call from the link_to attribute will send attributes only
       params.permit(:metric_id, :event_id, :duser_id, :start_dt, :end_dt, :span, :significant,:id,:testname)
      end
    end

    def show_params
      Rails.logger.info "review:params #{params.inspect}"
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_chart_image.html.erb
<%# reviewStats = local_assigns[:reviewStats] %>
<% if ! (defined?(reviewStats).nil?) %>
	<% Rails.logger.info " chart_image.html.erb chartImageFile is: #{ reviewStats.active_class.chartImageFile} " %>
	<div id="chart_image" style="height:600px;">
	  <%= image_tag("tmp/#{reviewStats.active_class.chartImageFile}") %>
	</div>
<%#  review = local_assigns.fetch(:review, @review) %>
<%else%>
	<% Rails.logger.info " chart_image.html.erb : No reviewStats local assign found "%>
 <%end%>
<%#=link_to 'show-chart', '#', remote: true ,hidden: true, id: "show-chart" %>
<%#=link_to 'my_link', reviews_show_regression_path(review.as_json), remote: true ,hidden: true, id: "show-chart" %>

<%#=link_to 'my_link', reviews_chart_path( review.as_json), remote: true ,hidden: true, id: "show-chart" %>
<%#  review = local_assigns.fetch(:review, @review) %>
<%#=
 #link_to 'my link', reviews_chart_path(review: @review), remote: true ,hidden: true, id: "show-chart"
%>

app/views/reviews/_chart_info.html.erb
<%#= chartSeries = local_assigns.fetch(:chartSeries) %>

<%# Rails.logger.info ("chart_info values:  #{chartSeries.show_result}") %>
<%if defined?(reviewStats) and !reviewStats.nil? %>

	<% chartSeries = reviewStats.active_class %>
	<p>
		<% chartSeries.messages.each_pair do  |key,value| %>
		 <dt><%= key %> </dt>
		 <% value.each do |line| %>
			<dd><%= line %> </dd>
		 <%end%>
		<%end%>
	</p>
	<h5>
<%else%>
	<%if defined? chart_active and chart_active %>
	<h2> 
		Sorry.  Something went wrong and we can't interpret the data. If the problem persists, please contact  whodabudda@gmail.com. 
	</h2>
	<%end%>
<%end%>

<% if false %>
<%end%>

app/views/reviews/_form.html.erb
<div class="show-review-form" >
<%  post_method = local_assigns.fetch(:post_method, false) %>
<%  review = local_assigns.fetch(:review, @review) %>
    <!--
      Here we conditionally render the form.  There is apparently a bug in Rails where 
      the 'form_with' helper cannot be in an if..end block because it can't determine if the end
      tag as an end to its 'do' loop or the 'if' statement, Therefore, we have to include all 
      the code inside the if..end block as opposed to just the 'form_with' fragment.
    -->
    <%# if post_method %>
    <%Rails.logger.info "FORM: post_method: #{post_method.to_s} persisted?: #{review.persisted?} review: #{review.inspect}" %>
      <%# byebug %>
    <%= form_with(model: review  , html: {id: 'review-form' }) do |form| %>
       <%= render partial: 'form_with_content',locals: {review: review, form: form,post_method: post_method} %>
    <% end %>
</div>
    <% if false %>
    <%# else %>
    <!--
      Bug apparently introduced at Rails 6.x where form_with doesn't create the data-remote attribute
      consistently, and the way to force it is to say local: false.
      https://stackoverflow.com/questions/45221800/rails-5-1-2-form-with-is-not-showing-data-remote-true-in-the-html
    -->

      <%=  form_with(model: review, method: :get, url:  url_for(controller: :reviews, action: :show_regression , id: review.id ), local: false) do |form|  %>
      <%= render partial: 'form_with_content',locals: {review: review, form: form,post_method: post_method} %>
      <% end %>
    <% end%>

app/views/reviews/_form_with_content.html.erb
<!--
  This partial will populate the fields for 2 different form tags.  The actual form tag is created in the "form.html.erb"for the GET and POST, but the POST is only called from 'show_regression.js.erb' 
  because we want only the submit button to show and then only if the form passes validations.
  If "post_method" is true, then all fields are hidden except 'submit' which calls the create action.
  Otherwise the 'show_regression' action is called.
-->
<%  review = local_assigns.fetch(:review, @review) %>
<%  post_method = local_assigns.fetch(:post_method, false) %>

  <% review.errors.clear %>
  <% review.valid? %>
  <%  Rails.logger.info "local_assigns in form_with_content: #{local_assigns}" %>
  <% if review.errors.any? %>
      <div id="review-model-error">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%# Rails.logger.info "review data in form: post_method: #{post_method}  #{review.inspect}"%>
  <div class="form-group">
    <%= form.label :metric_id , class:"control-label" , hidden: post_method %>
    <% @m = Metric.where( " (duser_id = 1 or duser_id = ?) and series_type = ?", current_duser.id, "metric" ) %>
    <%= collection_select(:review,:metric_id,@m, :id, :name,{:selected => review.metric_id,prompt: true} ,onchange: "handleReviewChange()")%>
  </div>

  <div class="field" >
    <%= form.label :event_id %>
    <% @e = Metric.where( " (duser_id = 1 or duser_id = ?) and series_type = ?", current_duser.id, "event" ) %>
    <%= collection_select(:review,:event_id,@e, :id, :name,{:selected => review.event_id, prompt: true,required: true},onchange: "handleReviewChange()") %>
    <%#= select_tag 'Event', options_from_collection_for_select(@e, 'id', 'name',:selected => review.event_id ) %>
    <%#= collection_select(:metric,:id,@e, :id, :name) %>
  </div>
  <div class="field">
    <%= form.label :duser_id ,hidden: true%>
    <%= form.text_field :duser_id, value: current_duser.id, readonly: true,hidden: true,required: true%>
  </div>

  <!--  Use date_field instead of date_select because with date_field you get a calendar
        popup, and date_select incorrectly loads the selection fields when the page is refreshed
        TODO: Not sure why I was hiding fields if post_method is true.  Remove these conditions later when cleaning up
        the code.
  -->
  <div class="field" <%= post_method ? nil : nil%> >
    <%= form.label :start_dt %>
    <%= form.date_field :start_dt,required: true ,onchange: "handleReviewChange()" %>
  </div>

  <div class="field" <%= post_method ? nil : nil%> >
    <%= form.label :end_dt%>
    <%= form.date_field :end_dt,required: true, onchange: "handleReviewChange()"%>
  </div>

  <div class="field" <%= post_method ? nil : nil%>>
    <%= form.label :span %>
    <%#= form.number_field :span %>
    <%# TODO  turn this into an input field with a range option %>
    <%= select :review,:span, options_for_select([ "24", "48" ,"72","96","120","144","168"],review.span ),{}, onchange: "handleReviewChange()"%>
  </div>

  <div class="field" <%= post_method ? nil : nil%>>
    <%= form.label :significant%>
    <%= form.check_box :significant , readonly: true%>
  </div>
  <div class="field">
    <%= form.label :id ,hidden: true%>
    <%= form.number_field :id , readonly: true, hidden: true%>
 </div>

  <% if review.valid? %>
    <div class="actions">
      <%= form.submit 'Save Review' %>
    </div>
  <%end%>

 <%=link_to 'my_link', reviews_show_regression_path(review.as_json), remote: true ,hidden: true, id: "show-chart" %>

<script>
function handleReviewChange() {
  // Serialize form data
  var formData = $('#review-form').serialize();

  // Set href attribute for the hidden link
  var newHref = '<%= reviews_show_regression_path %>' + '?' + formData;
  $('#show-chart').attr('href', newHref);

  // Trigger a click on the hidden link
  document.getElementById('show-chart').click();
}
</script>

app/views/reviews/_regression_chart_info.html.erb
<%#= chartSeries = local_assigns.fetch(:chartSeries) %>

<%if defined?(reviewStats) and !reviewStats.nil? %>

	<% chartSeries = reviewStats.active_class %>
	<% pearson_r = "an unknown" %>

	<% 
	case  chartSeries.pearson_r.to_f.abs 
	when  0.0..0.3
		pearson_r = "a weak"
	when  0.3.. 0.5
		pearson_r = "a moderate"
	when  0.5..1.0
		pearson_r = "a strong"
	end
	%>

	<p>
		<% chartSeries.messages.each_pair do  |key,value| %>
		 <dt><%= key %> </dt>
		 <% value.each do |line| %>
			<dd><%= line %> </dd>
		 <%end%>
		<%end%>
	</p>
	<h5>
		Based on the pearson r value, there appears to be <%= "#{pearson_r}"%> relationship between these two variables.
	</h5>
	<p>
		Keep in mind that even if a correlation is statistically significant, it does not imply causation. It only indicates that there is a relationship between the variables. Establishing causation requires additional evidence and study design.
	</p>
	<br><br>
	<h3> The regression line variables:  <%=chartSeries.show_result%> </h3>
<%else%>
	<%if defined? chart_active and chart_active %>
	<h2> 
		Sorry.  Something went wrong and we can't interpret the data. If the problem persists, please contact  whodabudda@gmail.com. 
	</h2>
	<%end%>
<%end%>

<% if false %>
<%end%>

app/views/reviews/_stat_links.html.erb
<style type="text/css">
  .checkmark  {
    font-style: italic;
    font-size: smaller;
    color: green;
  }
  .checkmark:after {
      content: '\2713';
      color: green;
      padding: 5px;
  }
</style>
<% reviewStats = local_assigns.fetch(:reviewStats) %>
<% Rails.logger.info ("***********in stat_links partial reviewStats?:  #{!reviewStats.nil?}") %>
<%if defined?(reviewStats) and !reviewStats.nil? %>
  <%# Rails.logger.info ("*********in stat_links partial chartSeries:  #{chartSeries.inspect}") %>
  <% @review = reviewStats.review.dup %>
  <ul class="stat-links list-group list-group-horizontal" >
    <% reviewStats.stat_classes.each do |m| %>
      <li>
        <%=link_to m, reviews_show_regression_path(review: @review.as_json, testname: m),remote: true,  class: "list-group-item border-0 checkmark toggle_metric" %>
      </li>
      <li>
      <% end %>
    </ul>
  <% end %>
  <% if false %>
    <%#= link_to m,  { @review , testname: m, remote: true, controller:"reviews" , action: "show_regression" } , {class: "list-group-item border-0 checkmark show_stat_chart"  } %>
  <%end%>

app/views/reviews/destroy.js.erb
<% if @review.errors.any? %>

  // Create a list of errors
  var errors = $('<ul />');

  <% @review.errors.full_messages.each do |error| %>
    errors.append('<li><%= escape_javascript(error) %></li>');
  <% end %>

  alert(errors)
<% else %>


  //
  //If there wasn't an error removing the row in the database, 
  //  1. remove the row from the table display
  //  2. remove the point from the chart
  //
  $("#tr_review_<%=@review.id%>").remove()

<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/home.html.erb
<%#  require_dependency('h_s_series_base') %>
<%#   require_dependency('h_s_series_regression') %>
<style>
  /* The sidebar menu */
  .sidenav {
    height: 80%; /* Full-height: remove this if you want "auto" height */
   /*  width: 160px; Set the width of the sidebar */
    position: relative; /* Fixed Sidebar (stay in place on scroll) */
    z-index: 0; /* Stay on top */
    top: 0; /* Stay at the top */
    left: 0;
    background-color: #f1f1f1; /* Black */
    /* overflow-x: hidden;  Disable horizontal scroll */
    padding-top: 20px;
  }
  /* When you mouse over the navigation links, change their color */
  .sidenav a:hover {
    color: blue;
  }
  .review-display {
      width: 80%;
  }
  #review-model-error {
  #}
</style>
<div class="container-fluid">
  <div class="row">
    <div id="review-home-erb" class="col-lg-2"> <!-- use col-lg-2 so that sidebar and chart stack when window is very small -->
      <%= render :partial => "shared/review_sidebar" ,locals: {review: @review}%>
    </div>
    <div  class="col-8">
      <%#= render partial: "chart" ,locals: {review: @review} if @review.valid?%>
      <div id="review-error" class="review-display" > </div>
      <div id="stat-links" >
        <%= render partial: "stat_links" ,locals: {reviewStats: @reviewStats}%>
      </div>
      <div id="review-chart" class="review-display">
        <%= render partial: "chart" ,locals: {review: @review}%>
      </div>
      <div id="review-info" class="review-display">
        <%= render partial: "chart_info" ,locals: {reviewStats: @reviewStats}%>
      </div>
    </div>
  </div>
</div>
<%#=image_tag("Rplot.jpg") %>
<%#= image_pack_tag("static/Rplot.jpg") %>
<%# if @review.metric_id&.nonzero?  and @review.event_id&.nonzero? %>
<script>
  var initialPage = "review_home"; // Assuming @page holds the page identifier
</script>
<%# end %>
<%# 
  obsolete code saved here in case it needs resurrection

 %>

app/views/reviews/select_modal.html.erb
<%= content_for :'modal-title'  do %>
   Select Review 
<%end%>
<%= content_for :'modal-body'  do %>

<p id="notice"><%= notice %></p>

<h1>Reviews</h1>
<%# @reviews = Review.all %>
<table class="thetable">
  <thead>
    <tr>
      <th>Metric</th>
      <th>Event</th>
      <th>Start dt</th>
      <th>End dt</th>
      <th>Span</th>
      <th>Significant</th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr id="tr_review_<%=review.id.to_s%>" >
        <td><%= review.metric.name %></td>
        <td><%= review.event.name %></td>
        <td><%= review.start_dt %></td>
        <td><%= review.end_dt %></td>
        <td><%= review.span %></td>
      	<td><%= review.significant %></td>
		    <td><%= link_to 'Select', reviews_home_path(id: review.id) %> </td>
        <td><%= link_to 'Remove', review, method: :delete ,remote: true%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', reviews_home_path %>
<%end%>

app/views/reviews/select_modal.js.erb
$("#modal-holder").html("<%= escape_javascript(render template: 'reviews/select_modal', formats: [:html], layout: 'layouts/modal') %>")
//new bootstrap.Modal(document.getElementById('exampleModal')).show()
showModal('exampleModal')
//$('#exampleModal').modal("show")

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Metric:</strong>
  <%= @review.metric_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @review.event_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.duser_id %>
</p>

<p>
  <strong>Start dt:</strong>
  <%= @review.start_dt %>
</p>

<p>
  <strong>End dt:</strong>
  <%= @review.end_dt %>
</p>

<p>
  <strong>Span:</strong>
  <%= @review.span %>
</p>

<p>
  <strong>Significant:</strong>
  <%= @review.significant %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/stat_test_display.js.erb
<%   require_dependency('h_s_series_base') %>
<%   require_dependency('h_s_series_regression') %>

<% if false %>
<%=  Rails.logger.info "We made it into the show_regression.js.erb file" %>
<%=  Rails.logger.info "Chart name is: #{ @chart_mgr.chart_title_text} " %>
<% @review = (@tempreview.nil? ?  @review : @tempreview )%>
<%  end %>

<%# @chartSeries = (@chartSeries.nil? ?  nil : @chartSeries )%>
<%#=  Rails.logger.info "ShowRegression.js_erb chartSeries is:  #{ @chartSeries.inspect} " %>

        var reg_series = JSON.parse('<%= raw @chartSeries.write.to_json %>')
        var reg_series_line = JSON.parse('<%= raw @chartSeries.getRegValues.to_json %>')
        console.log(reg_series)
        console.log(reg_series_line)
        chart1.addSeries(reg_series)
        chart1.addSeries(reg_series_line)
        chart1.reflow()
        //
        //
        //document.getElementById("review-info").replaceWith("<%= j ("#{render partial: 'chart_info', locals: {  chartSeries: @chartSeries}}").html_safe %>");
        document.getElementById("review-info").innerHTML =  ("<%= j ("#{render partial: 'chart_info', locals: {  chartSeries: @chartSeries, chart_active: true }}").html_safe %>")
        document.getElementById("review-error").innerText = '';
      <%else%>
        // document.getElementById("review-error").value = <%#= @chartSeries.error_msg %>;
         document.getElementById("review-info").innerHTML = '';
         document.getElementById("review-error").innerText = '<%= @chartSeries.error_msg %>';
         console.log("changed review-error")
      <% end %>

    //
    //adds the series to the chart, along with all series options
    //the options are different for events vs metrics.  
    //Events are charted as STD DEV points in a scatter graph, but the actual values are 
    //included as data and displayed in the Tooltip
    //